backend:
  name: git-gateway
  repo: mahmudnibir/My-Porfolio   # your GitHub repo
  branch: main                    # or 'master' if your default branch

media_folder: "assests/images/uploads"
public_folder: "/assests/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Bio", name: "bio", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "assests/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
