backend:
  name: github
  repo: mahmudnibir/My-Porfolio   # replace with your GitHub username/repo if different
  branch: main                           # or 'master' if your default branch
  auth_type: "token"
  token: "{{ GIT_TOKEN }}"            # pulls the token from Netlify environment variable

media_folder: "assests/images/uploads"   # folder where images will be saved
public_folder: "/assests/images/uploads" # path used in your site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Header Text", name: "header", widget: "string" }
          - { label: "About Section", name: "about", widget: "markdown" }
          - { label: "Contact Info", name: "contact", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "assests/projects"      # folder where project entries will be stored
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Project Description", name: "description", widget: "markdown" }
      - { label: "Project Image", name: "image", widget: "image" }
